export const services = [
  {
    id: 1,
    Name: "Frontend Dev",
    indicator: "Front",
    state: "true",
    Skills: [
      "Testing",
      "UX/UI",
      "React",
      "NextJS",
      "Jest",
      "JavaScript",
      "TypeScript",
      "Tailwind",
      "HTML",
      "CSS",
    ],
  },
  {
    id: 2,
    Name: "Backend Dev",
    indicator: "Back",
    state: "true",
    Skills: [
      "CRUD",
      "Restful API",
      "NodeJS",
      "ExpressJS",
      "Python",
      "Imnsonia",
      "Postman",
    ],
  },
  {
    id: 3,
    Name: "Databases",
    indicator: "Data",
    state: "true",
    Skills: ["SQL", "NoSQL", "PostgreSQL", "MySQL", "MongoDB", "Mongoose"],
  },

  {
    id: 4,
    Name: "Extra Technologies",
    indicator: "Extra",
    state: "true",
    Skills: [
      "Git",
      "GitHub",
      "Gitkraken",
      "Vercel",
      "Excel",
      "Access",
      "Figma",
      "Jira",
    ],
  },
  {
    id: 5,
    Name: "Cloud (In progress)",
    indicator: "cloud",
    state: "false",
    Skills: ["AWS", "Azure", "Docker", "Kubernetes"],
  },
];

export const friends = [
  {
    id: 1,
    name: "Marco Figueroa",
    work: "Frontend Dev",
    webSite: "https://gabo-na.vercel.app/",
  },
  {
    id: 2,
    name: "Josue Urquizo",
    work: "Frontend Dev",
    webSite: "https://gabo-na.vercel.app/",
  },
  {
    id: 3,
    name: "Gonzalo Cuadros",
    work: "Frontend Dev",
    webSite: "https://gabo-na.vercel.app/",
  },
  {
    id: 4,
    name: "Valeria Cervantes",
    work: "Frontend Dev",
    webSite: "https://gabo-na.vercel.app/",
  },
  {
    id: 5,
    name: "Luciana Gutierrez",
    work: "Frontend Dev",
    webSite: "https://gabo-na.vercel.app/",
  },
  {
    id: 6,
    name: "Alejandra Mamani",
    work: "Frontend Dev",
    webSite: "https://gabo-na.vercel.app/",
  },
];

export const projectsCard = [
  {
    id: 1,
    image: "https://via.placeholder.com/150",
    name: "Project 1",
    description: "Description 1",
    technologies: ["React", "NodeJS", "MongoDB"],
    webSite: "...",
    githubRepository: "...",
  },
  {
    id: 2,
    image: "https://via.placeholder.com/150",
    name: "Project 2",
    description: "Description 2",
    technologies: ["React", "NodeJS", "MongoDB"],
    webSite: "...",
    githubRepository: "...",
  },
  {
    id: 3,
    image: "https://via.placeholder.com/150",
    name: "Project 3",
    description: "Description 3",
    technologies: ["React", "NodeJS", "MongoDB"],
    webSite: "...",
    githubRepository: "...",
  },
  {
    id: 4,
    image: "https://via.placeholder.com/150",
    name: "Project 4",
    description: "Description 4",
    technologies: ["React", "NodeJS", "MongoDB"],
    webSite: "...",
    githubRepository: "...",
  },
  {
    id: 5,
    image: "https://via.placeholder.com/150",
    name: "Project 5",
    description: "Description 5",
    technologies: ["React", "NodeJS", "MongoDB"],
    webSite: "...",
    githubRepository: "...",
  },
];
