export const services = [
  {
    id: 1,
    Name: "Frontend Developer",
    indicator: "Front",
    state: "true",
    Skills: [
      "Testing",
      "UX/UI",
      "React",
      "NextJS",
      "Jest",
      "JavaScript",
      "TypeScript",
      "Tailwind",
      "HTML",
      "CSS",
    ],
  },
  {
    id: 2,
    Name: "Backend Developer",
    indicator: "Back",
    state: "true",
    Skills: [
      "CRUD",
      "Restful API",
      "NodeJS",
      "ExpressJS",
      "Python",
      "Imnsonia",
      "Postman",
    ],
  },
  {
    id: 3,
    Name: "Databases",
    indicator: "Data",
    state: "true",
    Skills: ["SQL", "NoSQL", "PostgreSQL", "MySQL", "MongoDB", "Mongoose"],
  },

  {
    id: 4,
    Name: "Extra Technologies",
    indicator: "Extra",
    state: "true",
    Skills: [
      "Git",
      "GitHub",
      "Gitkraken",
      "Vercel",
      "Excel",
      "Access",
      "Figma",
      "Jira",
    ],
  },
  {
    id: 5,
    Name: "Cloud (In progress)",
    indicator: "cloud",
    state: "false",
    Skills: ["AWS", "Azure", "Docker", "Kubernetes"],
  },
];
